### ISSUE TITLE
Parsing and encoding problems

### ISSUE THREAD

**Issue by ahmetcanaydemir** [berkekurnaz/Turkiye-Deprem-Api#1]
Nice project Berke!
But there is some problems about parsing cities. Also UTF-8 encoding needed for API page.

![image](https://user-images.githubusercontent.com/8572957/73244385-e3375c00-41ba-11ea-9a4c-d5ed75eee302.png)

**Comment by berkekurnaz** [comment]
Thanks Ahmet.  We just learned this problem and solved it quickly.
