### ISSUE TITLE
son iki item null geliyor

### ISSUE THREAD

**Issue by smurat** [berkekurnaz/Turkiye-Deprem-Api#2]
eline sağlık Berke. Api'den gelen son iki item  boş geliyor gibi sanki. 500 item sorunsuz var +2 tane boş eleman var galiba.

![https   kandilli herokuapp com api](https://user-images.githubusercontent.com/51034904/73449285-db6ee780-4373-11ea-8ee6-52281912f418.png)

**Comment by berkekurnaz** [comment]
Merhaba Murat. Bahsettiğin sorunu farkettim ve hemen çözdüm. İlgin için teşekkür ediyorum.
